var fs = require("fs")
var path = require("path")

var set = fs.readFileSync(path.join(__dirname, 'set.txt'), 'utf-8').split('\r\n')

var src = fs.readFileSync(path.join(__dirname, 'src.css'), 'utf-8')

var iconRegex = /.(.+):before {[\r\n]+ +content: +(.+);[\r\n]+}[\r\n]+/g

let matches = Array.from(src.matchAll(iconRegex))

let data = Array.from(matches)
    .map(e => {
        return {
            src: e[0],
            name: e[1],
            data: e[2]
        }
    })
    .filter(e => set.includes(e.name))

let icons = data
    .map(e => `.${e.name}:before { content: ${e.data}; }`)
    .join('\r\n')

let file = "/* autogenerated file */\r\n\r\n" + icons

fs.writeFileSync(path.join(__dirname, '../assets/iconset.css'), file)